name: azp-agent-linux
services:
  azp-agent-linux-0:
    container_name: azp-agent-linux-0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      - AZP_AGENT_NAME=azp-agent-linux-0

  azp-agent-linux-1:
    container_name: azp-agent-linux-1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      - AZP_AGENT_NAME=azp-agent-linux-1

  azp-agent-linux-2:
    container_name: azp-agent-linux-2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      - AZP_AGENT_NAME=azp-agent-linux-2
